export const SERVICES_LIST_REQUEST = 'SEARCH_SKILLS_REQUEST';
export const SERVICES_LIST_FAILURE = 'SEARCH_SKILLS_FAILURE';
export const SERVICES_LIST_SUCCESS = 'SEARCH_SKILLS_SUCCESS';

export const ITEM_DETAIL_REQUEST = 'SEARCH_SKILLS_REQUEST';
export const ITEM_DETAIL_FAILURE = 'SEARCH_SKILLS_FAILURE';
export const ITEM_DETAIL_SUCCESS = 'SEARCH_SKILLS_SUCCESS';